package schema

import (
	"fmt"
	"strings"

	wt "github.com/theworker02/wiretap/pkg/wiretap"
)

// GenerateGo emits idiomatic ParseX code with bounds checks and typed errors.
func GenerateGo(s *Schema, pkg string) (string, error) {
	if s == nil {
		return "", wt.ErrSchemaInvalid
	}
	if pkg == "" {
		pkg = "protocol"
	}
	typeName := exportName(s.Name)
	var b strings.Builder
	b.WriteString("// Code generated by wiretap generate. DO NOT EDIT.\n")
	b.WriteString("// Schema: " + s.Name + "\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"encoding/binary\"\n\t\"fmt\"\n)\n\n")
	b.WriteString("// ParseError is returned when input does not match the schema.\n")
	b.WriteString("type ParseError struct {\n\tField string\n\tMsg   string\n}\n\n")
	b.WriteString("func (e *ParseError) Error() string {\n\treturn fmt.Sprintf(\"parse %s: %s\", e.Field, e.Msg)\n}\n\n")

	var emitTypes func(fields []Field, prefix string)
	emitTypes = func(fields []Field, prefix string) {
		for _, f := range fields {
			if f.Type == "struct" {
				tn := prefix + exportName(f.Name)
				fmt.Fprintf(&b, "// %s is a nested structure.\ntype %s struct {\n", tn, tn)
				for _, c := range f.Children {
					fmt.Fprintf(&b, "\t%s %s // %s\n", exportName(c.Name), fieldGoType(c, tn), c.Description)
				}
				b.WriteString("}\n\n")
				emitTypes(f.Children, tn)
			}
			if f.Type == "array" && len(f.Children) > 1 {
				tn := prefix + exportName(f.Name) + "Elem"
				fmt.Fprintf(&b, "type %s struct {\n", tn)
				for _, c := range f.Children {
					fmt.Fprintf(&b, "\t%s %s\n", exportName(c.Name), goType(c))
				}
				b.WriteString("}\n\n")
			}
		}
	}
	emitTypes(s.Fields, typeName)

	fmt.Fprintf(&b, "// %s is a parsed message.\ntype %s struct {\n", typeName, typeName)
	for _, f := range s.Fields {
		fmt.Fprintf(&b, "\t%s %s // %s\n", exportName(f.Name), fieldGoType(f, typeName), f.Description)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// Parse%s parses a %s message. It never panics; truncated input returns *ParseError.\n", typeName, s.Name)
	fmt.Fprintf(&b, "func Parse%s(data []byte) (*%s, error) {\n", typeName, typeName)
	fmt.Fprintf(&b, "\tout := &%s{}\n", typeName)
	writeFields(&b, s.Fields, "out", typeName)
	b.WriteString("\treturn out, nil\n}\n")
	return b.String(), nil
}

func fieldGoType(f Field, parent string) string {
	switch f.Type {
	case "struct":
		return parent + exportName(f.Name)
	case "array":
		elemSize := f.Length
		if elemSize == 0 {
			if v, ok := asInt(f.Meta["element_size"]); ok {
				elemSize = v
			}
		}
		if len(f.Children) == 1 && f.Children[0].Type == "bytes" {
			return "[][]byte"
		}
		if len(f.Children) > 1 {
			return "[]" + parent + exportName(f.Name) + "Elem"
		}
		if len(f.Children) == 1 {
			return "[]" + goType(f.Children[0])
		}
		_ = elemSize
		return "[][]byte"
	default:
		return goType(f)
	}
}

func writeFields(b *strings.Builder, fields []Field, dest, typePrefix string) {
	for _, f := range fields {
		switch f.Type {
		case "struct":
			writeStructAssign(b, f, dest, typePrefix)
		case "array":
			writeArrayAssign(b, f, dest, typePrefix)
		default:
			writeScalar(b, f, dest)
		}
	}
}

func writeStructAssign(b *strings.Builder, f Field, dest, typePrefix string) {
	tn := typePrefix + exportName(f.Name)
	ename := exportName(f.Name)
	fmt.Fprintf(b, "\t{\n\t\tst := %s{}\n", tn)
	writeFields(b, f.Children, "st", tn)
	fmt.Fprintf(b, "\t\t%s.%s = st\n\t}\n", dest, ename)
}

func writeArrayAssign(b *strings.Builder, f Field, dest, typePrefix string) {
	ename := exportName(f.Name)
	elemSize := f.Length
	if elemSize <= 0 {
		if v, ok := asInt(f.Meta["element_size"]); ok {
			elemSize = v
		} else {
			elemSize = 4
		}
	}
	arrOff := 0
	if f.Offset != nil {
		arrOff = *f.Offset
	}
	countOff, hasCount := asInt(f.Meta["count_offset"])
	cw, _ := asInt(f.Meta["count_width"])
	endian, _ := f.Meta["endian"].(string)
	if endian == "" {
		endian = "be"
	}
	fmt.Fprintf(b, "\t{\n")
	if hasCount && cw > 0 {
		fmt.Fprintf(b, "\t\tif len(data) < %d {\n\t\t\treturn nil, &ParseError{Field: %q, Msg: \"truncated count field\"}\n\t\t}\n", countOff+cw, f.Name)
		switch cw {
		case 1:
			fmt.Fprintf(b, "\t\tn := int(data[%d])\n", countOff)
		case 2:
			if endian == "le" {
				fmt.Fprintf(b, "\t\tn := int(binary.LittleEndian.Uint16(data[%d:%d]))\n", countOff, countOff+2)
			} else {
				fmt.Fprintf(b, "\t\tn := int(binary.BigEndian.Uint16(data[%d:%d]))\n", countOff, countOff+2)
			}
		default:
			if endian == "le" {
				fmt.Fprintf(b, "\t\tn := int(binary.LittleEndian.Uint32(data[%d:%d]))\n", countOff, countOff+4)
			} else {
				fmt.Fprintf(b, "\t\tn := int(binary.BigEndian.Uint32(data[%d:%d]))\n", countOff, countOff+4)
			}
		}
	} else if n, ok := asInt(f.Meta["count"]); ok {
		fmt.Fprintf(b, "\t\tn := %d\n", n)
	} else {
		fmt.Fprintf(b, "\t\tn := 0\n\t\tif rem := len(data)-%d; rem >= %d { n = rem / %d }\n", arrOff, elemSize, elemSize)
	}
	fmt.Fprintf(b, "\t\tif n < 0 || %d+n*%d > len(data) {\n\t\t\treturn nil, &ParseError{Field: %q, Msg: fmt.Sprintf(\"array bounds n=%%d need %%d have %%d\", n, %d+n*%d, len(data))}\n\t\t}\n",
		arrOff, elemSize, f.Name, arrOff, elemSize)
	fmt.Fprintf(b, "\t\tarr := make([][]byte, n)\n")
	fmt.Fprintf(b, "\t\tfor i := 0; i < n; i++ {\n\t\t\to := %d + i*%d\n\t\t\tarr[i] = append([]byte(nil), data[o:o+%d]...)\n\t\t}\n", arrOff, elemSize, elemSize)
	fmt.Fprintf(b, "\t\t%s.%s = arr\n\t}\n", dest, ename)
	_ = typePrefix
}

func writeScalar(b *strings.Builder, f Field, dest string) {
	if f.Offset == nil {
		return
	}
	off, length := *f.Offset, f.Length
	if length == 0 {
		length = defaultLen(f.Type)
	}
	fmt.Fprintf(b, "\tif len(data) < %d {\n\t\treturn nil, &ParseError{Field: %q, Msg: fmt.Sprintf(\"need %%d bytes, have %%d\", %d, len(data))}\n\t}\n",
		off+length, f.Name, off+length)
	ename := exportName(f.Name)
	endian := f.Endian
	if endian == "" {
		endian = "be"
	}
	assign := dest + "." + ename
	switch {
	case strings.HasPrefix(f.Type, "u8") || f.Type == "bitfield":
		fmt.Fprintf(b, "\t%s = data[%d]\n", assign, off)
	case f.Type == "u16":
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = binary.LittleEndian.Uint16(data[%d:%d])\n", assign, off, off+2)
		} else {
			fmt.Fprintf(b, "\t%s = binary.BigEndian.Uint16(data[%d:%d])\n", assign, off, off+2)
		}
	case f.Type == "u32":
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = binary.LittleEndian.Uint32(data[%d:%d])\n", assign, off, off+4)
		} else {
			fmt.Fprintf(b, "\t%s = binary.BigEndian.Uint32(data[%d:%d])\n", assign, off, off+4)
		}
	case f.Type == "u64":
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = binary.LittleEndian.Uint64(data[%d:%d])\n", assign, off, off+8)
		} else {
			fmt.Fprintf(b, "\t%s = binary.BigEndian.Uint64(data[%d:%d])\n", assign, off, off+8)
		}
	case f.Type == "string":
		fmt.Fprintf(b, "\t%s = string(data[%d:%d])\n", assign, off, off+length)
	case f.Type == "checksum" && length == 2:
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = binary.LittleEndian.Uint16(data[%d:%d])\n", assign, off, off+2)
		} else {
			fmt.Fprintf(b, "\t%s = binary.BigEndian.Uint16(data[%d:%d])\n", assign, off, off+2)
		}
	case f.Type == "checksum" && length == 4:
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = binary.LittleEndian.Uint32(data[%d:%d])\n", assign, off, off+4)
		} else {
			fmt.Fprintf(b, "\t%s = binary.BigEndian.Uint32(data[%d:%d])\n", assign, off, off+4)
		}
	case f.Type == "checksum" && length == 1:
		fmt.Fprintf(b, "\t%s = data[%d]\n", assign, off)
	case f.Type == "i8":
		fmt.Fprintf(b, "\t%s = int8(data[%d])\n", assign, off)
	case f.Type == "i16":
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = int16(binary.LittleEndian.Uint16(data[%d:%d]))\n", assign, off, off+2)
		} else {
			fmt.Fprintf(b, "\t%s = int16(binary.BigEndian.Uint16(data[%d:%d]))\n", assign, off, off+2)
		}
	case f.Type == "i32":
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = int32(binary.LittleEndian.Uint32(data[%d:%d]))\n", assign, off, off+4)
		} else {
			fmt.Fprintf(b, "\t%s = int32(binary.BigEndian.Uint32(data[%d:%d]))\n", assign, off, off+4)
		}
	case f.Type == "i64":
		if endian == "le" {
			fmt.Fprintf(b, "\t%s = int64(binary.LittleEndian.Uint64(data[%d:%d]))\n", assign, off, off+8)
		} else {
			fmt.Fprintf(b, "\t%s = int64(binary.BigEndian.Uint64(data[%d:%d]))\n", assign, off, off+8)
		}
	default:
		fmt.Fprintf(b, "\t%s = append([]byte(nil), data[%d:%d]...)\n", assign, off, off+length)
	}
}
