package schema

import (
	"fmt"
	"strings"
)

// GenerateKaitai emits a Kaitai Struct (.ksy) YAML definition from a Wiretap schema.
func GenerateKaitai(s *Schema) (string, error) {
	if s == nil || s.Name == "" {
		return "", fmt.Errorf("invalid schema")
	}
	id := kaitaiID(s.Name)
	endian := "be"
	if s.Endian == "le" {
		endian = "le"
	}
	var b strings.Builder
	b.WriteString("# Generated by wiretap generate kaitai — review before trusting.\n")
	b.WriteString("meta:\n")
	fmt.Fprintf(&b, "  id: %s\n", id)
	fmt.Fprintf(&b, "  title: %s\n", s.Name)
	fmt.Fprintf(&b, "  endian: %s\n", endian)
	if s.Notes != "" {
		fmt.Fprintf(&b, "  doc: %q\n", s.Notes)
	}
	b.WriteString("seq:\n")
	writeKaitaiFields(&b, s.Fields, "  ")
	return b.String(), nil
}

func writeKaitaiFields(b *strings.Builder, fields []Field, indent string) {
	for _, f := range fields {
		id := kaitaiID(f.Name)
		fmt.Fprintf(b, "%s- id: %s\n", indent, id)
		if f.Description != "" {
			fmt.Fprintf(b, "%s  doc: %q\n", indent, f.Description)
		}
		switch f.Type {
		case "struct":
			fmt.Fprintf(b, "%s  type: %s\n", indent, id+"_t")
		case "array":
			elemSize := f.Length
			if elemSize <= 0 {
				elemSize = 1
			}
			fmt.Fprintf(b, "%s  size: %d\n", indent, elemSize)
			fmt.Fprintf(b, "%s  repeat: eos\n", indent)
			if n, ok := asInt(f.Meta["count"]); ok {
				fmt.Fprintf(b, "%s  # wiretap hint: fixed count=%d\n", indent, n)
			}
		case "string":
			if f.Length > 0 {
				fmt.Fprintf(b, "%s  type: str\n", indent)
				fmt.Fprintf(b, "%s  size: %d\n", indent, f.Length)
				fmt.Fprintf(b, "%s  encoding: ASCII\n", indent)
			} else {
				fmt.Fprintf(b, "%s  type: strz\n", indent)
				fmt.Fprintf(b, "%s  encoding: ASCII\n", indent)
			}
		case "bytes":
			n := f.Length
			if n <= 0 {
				n = 1
			}
			fmt.Fprintf(b, "%s  size: %d\n", indent, n)
		case "checksum":
			kt := kaitaiIntType(f)
			fmt.Fprintf(b, "%s  type: %s\n", indent, kt)
			fmt.Fprintf(b, "%s  doc: \"checksum field — verify externally\"\n", indent)
		case "bitfield":
			fmt.Fprintf(b, "%s  type: u1\n", indent)
		default:
			fmt.Fprintf(b, "%s  type: %s\n", indent, kaitaiIntType(f))
		}
	}
}

func kaitaiIntType(f Field) string {
	endian := f.Endian
	switch f.Type {
	case "u8", "i8", "bitfield":
		if strings.HasPrefix(f.Type, "i") {
			return "s1"
		}
		return "u1"
	case "u16":
		if endian == "le" {
			return "u2le"
		}
		return "u2"
	case "u32", "checksum":
		if f.Length == 2 {
			if endian == "le" {
				return "u2le"
			}
			return "u2"
		}
		if f.Length == 1 {
			return "u1"
		}
		if endian == "le" {
			return "u4le"
		}
		return "u4"
	case "u64":
		if endian == "le" {
			return "u8le"
		}
		return "u8"
	case "i16":
		if endian == "le" {
			return "s2le"
		}
		return "s2"
	case "i32":
		if endian == "le" {
			return "s4le"
		}
		return "s4"
	case "i64":
		if endian == "le" {
			return "s8le"
		}
		return "s8"
	default:
		if f.Length == 1 {
			return "u1"
		}
		if f.Length == 2 {
			return "u2"
		}
		if f.Length == 4 {
			return "u4"
		}
		return "u1"
	}
}

func kaitaiID(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for i, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else if r == '-' || r == ' ' {
			b.WriteByte('_')
		} else if i == 0 {
			b.WriteByte('f')
		}
	}
	out := b.String()
	if out == "" {
		return "field"
	}
	if out[0] >= '0' && out[0] <= '9' {
		return "f_" + out
	}
	return out
}

// GenerateWiresharkLua emits a stub Lua dissector for Wireshark.
func GenerateWiresharkLua(s *Schema, protoName string) (string, error) {
	if s == nil || s.Name == "" {
		return "", fmt.Errorf("invalid schema")
	}
	if protoName == "" {
		protoName = kaitaiID(s.Name)
	}
	filter := strings.ReplaceAll(protoName, "_", ".")
	var b strings.Builder
	b.WriteString("-- Generated by wiretap generate wireshark — stub dissector; review before use.\n")
	b.WriteString("-- Authorized captures only. This is not a network acquisition tool.\n\n")
	fmt.Fprintf(&b, "local p_%s = Proto(\"%s\", \"%s\")\n\n", protoName, filter, s.Name)
	for _, f := range s.Fields {
		id := kaitaiID(f.Name)
		ft := wiresharkFType(f)
		fmt.Fprintf(&b, "local f_%s = ProtoField.%s(\"%s.%s\", \"%s\")\n", id, ft, filter, id, f.Name)
	}
	b.WriteString("\np_" + protoName + ".fields = {")
	for i, f := range s.Fields {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "f_%s", kaitaiID(f.Name))
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "function p_%s.dissector(buf, pkt, tree)\n", protoName)
	fmt.Fprintf(&b, "  if buf:len() == 0 then return end\n")
	fmt.Fprintf(&b, "  pkt.cols.protocol = \"%s\"\n", s.Name)
	fmt.Fprintf(&b, "  local t = tree:add(p_%s, buf())\n", protoName)
	for _, f := range s.Fields {
		if f.Offset == nil {
			fmt.Fprintf(&b, "  -- field %s has no fixed offset; extend manually\n", f.Name)
			continue
		}
		off, length := *f.Offset, f.Length
		if length <= 0 {
			length = defaultLen(f.Type)
		}
		id := kaitaiID(f.Name)
		fmt.Fprintf(&b, "  if buf:len() >= %d then\n", off+length)
		fmt.Fprintf(&b, "    t:add(f_%s, buf(%d, %d))\n", id, off, length)
		b.WriteString("  end\n")
	}
	b.WriteString("end\n\n")
	b.WriteString("-- Register on a UDP/TCP port of your choosing after review:\n")
	fmt.Fprintf(&b, "-- local udp_table = DissectorTable.get(\"udp.port\")\n")
	fmt.Fprintf(&b, "-- udp_table:add(XXXX, p_%s)\n", protoName)
	return b.String(), nil
}

func wiresharkFType(f Field) string {
	switch f.Type {
	case "u8", "bitfield":
		return "uint8"
	case "u16":
		return "uint16"
	case "u32", "checksum":
		if f.Length == 2 {
			return "uint16"
		}
		if f.Length == 1 {
			return "uint8"
		}
		return "uint32"
	case "u64":
		return "uint64"
	case "i8":
		return "int8"
	case "i16":
		return "int16"
	case "i32":
		return "int32"
	case "string":
		return "string"
	case "bytes", "array", "struct":
		return "bytes"
	default:
		return "bytes"
	}
}
